sudo: required

language: node_js

services:
  - docker

before_script:
  - make build

script:
  - make test
  - make lint-macros
  - make test-macros

notifications:
  email:
    - rjohnson@mozilla.com
